#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=24        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=0  \
                 padding_right=0 \
                 color=$BAR_COLOR \
                 corner_radius=999 \
                 shadow=off       \
                 y_offset=3       \
                 margin=6         \
                 topmost=window \
                 border_width=2  \
                 border_color=$BAR_COLOR

# bar=(
#   corner_radius=12
#   height=33
#   color=$BAR_COLOR
#   border_width=2
#   border_color=$BAR_BORDER_COLOR
#   shadow=off
#   position=top
#   sticky=on
#   y_offset=1
#   margin=6
#   topmost=window
# )
##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:Bold:12.0"  \
                     icon.color=$ACCENT_COLOR                 \
                     label.font="SF Pro:Semibold:12.0" \
                     label.color=$ACCENT_COLOR                \
                     background.corner_radius=999            \
                     background.height=24                  \
                     background.color=$BAR_COLOR                  \
                     padding_left=0                        \
                     padding_right=10                       \
                     label.padding_left=4                  \
                     label.padding_right=10                \
                     icon.padding_left=10                  \
                     icon.padding_right=4                 \

sketchybar --add event aerospace_workspace_change
sketchybar --add event space_windows_change

# -- Left Side Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $PLUGIN_DIR/icon_map_fn.sh
# source ./icon_map.sh
# __icon_map "${app_name}"
# symbol_ligature="${icon_result}"
##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update